spring:
  kafka:
    properties:
      session:
        timeout:
          ms: 45000
      bootstrap:
        servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: info